name: Deploy School App

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
      ENV_FILE_PATH: /home/ubuntu/school/.env/.env.production
      PROJECT_DIR: school-backend
      APP_NAME: school-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Verify Node.js and npm installation
            node -v || { echo "Node.js not found"; exit 1; }
            npm -v || { echo "npm not found"; exit 1; }

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Clone the repository or pull the latest changes
            if [ -d "${{ env.PROJECT_DIR }}" ]; then
              cd ${{ env.PROJECT_DIR }}
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} ${{ env.PROJECT_DIR }}
              cd ${{ env.PROJECT_DIR }}
            fi

            # Install dependencies
            cd school-backend
            npm install

            # Copy environment file
            if [ -f "${{ env.ENV_FILE_PATH }}" ]; then
              cp ${{ env.ENV_FILE_PATH }} .env
            else
              echo ".env file missing at ${{ env.ENV_FILE_PATH }}"
              exit 1
            fi

            # Restart the application with PM2
            pm2 delete ${{ env.APP_NAME }} || true
            pm2 start npm --name ${{ env.APP_NAME }} -- run start
            pm2 save
