name: Deploy Node.js to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Your Windows server runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd C:\cbs-councelling-app\counseling-backend
          npm install

      - name: Restart App
        run: |
          cd C:\cbs-councelling-app\counseling-backend
          try {
            taskkill /IM node.exe /F
          } catch {
            Write-Output "Node was not running"
          }
          Start-Process "npm" -ArgumentList "start"
