name: Deploy Node.js to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Your Windows server runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Delete package-lock.json if exists to prevent EPERM
        run: |
          if exist "C:\cbs-councelling-app\counseling-backend\package-lock.json" (
            del /f "C:\cbs-councelling-app\counseling-backend\package-lock.json"
          )
        shell: cmd

      - name: Install dependencies
        run: |
          cd C:\cbs-councelling-app\counseling-backend
          npm install
        shell: cmd

      - name: Restart App
        run: |
          cd C:\cbs-councelling-app\counseling-backend
          pm2 restart app
        shell: cmd
